language: python
python:
- '2.7'
script: python script.py
deploy:
  provider: s3
  bucket: lvineeth-ebextensions
  acl: public_read
  region: eu-west-2
  endpoint: s3-us-west-2.amazonaws.com
env:
  global:
  - secure: WpfzYLs7trsaDbzaLnbyqzAWNT3HtJCmTQFWjrtb9REYGIUgWNHW45Vxe1rcrOGMsiWz78KEWwG/qM55rDUHm2BpEn1o1YpYXAht32Xc9q9QWcUhXDathSZilkwBF2ERwDjqP4zubruxALPFU/7E+hgavOr8P4UVEhUTurZawb71WfbVcLOek5vQwIkco0zG0ZXToMqp5AVbY1Kg1talDNmum+/OBSaPhtxmvirN9y0KRbs1JNg+RhvxfU63dqNOrxuNfPOe7s8P9zEGbN6or3ed/JRv3OLdvCMo7BUaxdZ/Ils4kPTgotxIQpiephI8/TiKBuiI3Ou95NzSaqTe5Dlxp30a/Xou7eXMe/DX7LGeJ5cJ2D+HHPe/e68yiYPb2guGVAiAnF11cMlDb4pAQbd/4eOf5dx4Hi2wQExvdDu9PIZYnlxQU9NtJe2kV2fHn1frGWfWbHOTOgmkMOGgIm3YoUlg5sedGwuWcLQGFY5o78WNd4ccDL4eieF8Xh6RL6q+XuX0OqoNtMkYrzLPAzM/Ifq3TwARNkvQHV98CwtPmTJ2h4aABIiud/4620dxDP4u6pFVvKXBVXXDYyR0Bw1VtWqtDlHLlzNRS665i4yULokFuy1/UkXgTQkAVXB5KnUAUIz6rW4bf8n17QCcBrAUA1672r0ubjPPzHBeNtw=
  - secure: dgdfp9st0JHCxIqf7IQVRSQtrLNzK8q6fL2raAaYWgyiluIGGibwwwdRM8eH0LQUYHSQ/KLkxxEdrxm8V9SfzJcEymgjuyOSw9nxR+WL6rTHVfEsSTaOrkGi8+6SeFriUyeC7AVlfBuuC4HLGgoB8xkXVzEKysfJGIQqSBf5e9yBqXMJxp8UgCkM1a6Dz+fZ4DDdJB2CVHIye2i2uCCfrAZB3gLwmeB8UyTIqV8RzsSmhHI09cFJbgLdnA7hR36Kr9wsDK7Vrfxs+WpZ479aJqFu1GFYxjN32I6/7krcp2uSgojRf3YFh+TgGhy+k2JiVYGubll0Fw5gokQ8xsQoWsxxeRbs81YObQl2Y/nqUunRFFUychDIO/A0CxuDjjQRCzcP9CeWUUPrYrIKqNVtu1/4jCjOGo9vcK8BG0j2vF7j9XNQBcPdbR1geTMS4HFch0ibLwgDNUkZBZoNLHuXCE9zXj1lW2CwiDjQjZNY8DMagMACGcrUtyoVViT5NGljOkYybMRCrpUXBpv1uw1yMAcjdcPfbcc86qa9agaj8A81Z3LdtfnxifaKEEtIlWSRuaaYzNnbUNNIMIlFovm5KIqfCTarTXfFqLkmQ53J7oslWhIIFEvSFO0zXxRXyUaO8Teap4sXlLPulOTKrzzTinZGISus5ggKg5R5nCEEQnE=
